### ISSUE TITLE
Change type of stimuli

### ISSUE THREAD

**Issue by hugofluhr** [hugofluhr/RewardPairsTask#11]
### Rational
We want to change the type of stimuli from geometric shapes to objects that have a well-established representation in the brain (e.g. faces, houses) to help with the fMRI data analysis. Ideally we would need 3 types of stimuli.

### Tasks
- [x] find 2 to 3 types of objects that have stable representations in the brain. backup with relevant literature.
- [x] add the image files
- [x] make the stimulus selection independent of rating
- [x] think how to assign stimuli to reward levels

**Comment by hugofluhr** [comment]
how to assign the reward levels and frequency levels:
- geometric shapes for lowest and highest reward level always
- for the others: stim A and B of same category need to have different reward level and different frequency.

**Comment by Vutya** [comment]
I'll take this issue
