### ISSUE TITLE
Changes to run at SNS lab

### ISSUE THREAD

**Issue by hugofluhr** [hugofluhr/RewardPairsTask#3]
Here are the changes we discussed that need to be made along with some information:
We can track the implementation here.

- [x] somewhere there is a semicolon missing in 2_2 (drawLines). done in #4 
- [x] remove the pc_id thing that is specific to the BLU lab. done in #4 
- [x] change which screen is being used by psychtoolbox. done in #4 
- [x] decrease the ITI in the practice phase (2_3) and specify it in the instructions. done in #5 
- [x] control box for MR: letters g and b, maybe add an MR parameter in the code. done in #5 
- [x] change the lines with session numbers, not 5 anymore, in all phases. done in #5 
- [x] add an end screen to the practice phase (2_3). done in #5 
- [x] think whether we want to set a seed for trial sequence generation?
- [x] increase the time where the chosen option is highlighted, just before the rewards are shown.
    need to figure out the specifics of the timing
- [x] payouts line 62 run.m does not work, naming of variables is not consistent.
- [x] think about payout scheme to make them more motivated.
   let's fix that and decide on the value of points later

**Comment by hugofluhr** [comment]
Stuff from PR #5 that we merged but think should be discussed/changed:

- [ ] We can maybe think of another way to call the "g" and "b" buttons as there are no letters drawn on the remote, maybe left/right as they won't see it when lying in the scanner?
- [ ] also let's discuss today what parts of the experiment are in/out of the scanner so we can change instructions accordingly.
- [ ] Will the participants need to input their IDs or will we do it?
